import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Event from '#models/event'
import { DateTime } from 'luxon'
import User from '#models/user'

export default class extends BaseSeeder {
  async run() {
    const users = await User.all()

    await Event.createMany([
      {
        title: 'Conférence Tech 2024',
        description: 'Une conférence sur les dernières technologies',
        date: DateTime.fromISO('2024-06-15T09:00:00'),
        location: 'Paris, France',
        image: 'https://example.com/event1.jpg',
        maxParticipants: 100,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop Développement Web',
        description: 'Apprentissage des bases du développement web',
        date: DateTime.fromISO('2024-07-01T10:00:00'),
        location: 'Lyon, France',
        image: 'https://example.com/event2.jpg',
        maxParticipants: 30,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Hackathon Innovation',
        description: '48h de développement intensif',
        date: DateTime.fromISO('2024-08-20T08:00:00'),
        location: 'Bordeaux, France',
        image: 'https://example.com/event3.jpg',
        maxParticipants: 50,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup AI & ML',
        description: "Échanges sur l'intelligence artificielle",
        date: DateTime.fromISO('2024-09-10T18:30:00'),
        location: 'Toulouse, France',
        image: 'https://example.com/event4.jpg',
        maxParticipants: 40,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Formation DevOps',
        description: 'Maîtrisez les outils DevOps',
        date: DateTime.fromISO('2024-10-05T09:00:00'),
        location: 'Nantes, France',
        image: 'https://example.com/event5.jpg',
        maxParticipants: 25,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Salon du Numérique',
        description: 'Découverte des innovations digitales',
        date: DateTime.fromISO('2024-11-15T10:00:00'),
        location: 'Lille, France',
        image: 'https://example.com/event6.jpg',
        maxParticipants: 200,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Webinaire Cybersécurité',
        description: 'Protection des données sensibles',
        date: DateTime.fromISO('2024-12-01T14:00:00'),
        location: 'En ligne',
        image: 'https://example.com/event7.jpg',
        maxParticipants: 100,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Conférence Blockchain',
        description: "L'avenir de la blockchain",
        date: DateTime.fromISO('2025-01-20T09:00:00'),
        location: 'Marseille, France',
        image: 'https://example.com/event8.jpg',
        maxParticipants: 80,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop UI/UX',
        description: "Design d'interfaces modernes",
        date: DateTime.fromISO('2025-02-10T10:00:00'),
        location: 'Strasbourg, France',
        image: 'https://example.com/event9.jpg',
        maxParticipants: 20,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup Cloud Computing',
        description: 'Solutions cloud innovantes',
        date: DateTime.fromISO('2025-03-05T18:30:00'),
        location: 'Nice, France',
        image: 'https://example.com/event10.jpg',
        maxParticipants: 35,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Hackathon Mobile',
        description: "Développement d'applications mobiles",
        date: DateTime.fromISO('2025-04-15T08:00:00'),
        location: 'Montpellier, France',
        image: 'https://example.com/event11.jpg',
        maxParticipants: 60,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Conférence Big Data',
        description: 'Analyse de données massives',
        date: DateTime.fromISO('2025-05-20T09:00:00'),
        location: 'Rennes, France',
        image: 'https://example.com/event12.jpg',
        maxParticipants: 90,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop IoT',
        description: 'Internet des Objets et applications',
        date: DateTime.fromISO('2025-06-10T10:00:00'),
        location: 'Grenoble, France',
        image: 'https://example.com/event13.jpg',
        maxParticipants: 25,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup DevOps',
        description: 'Pratiques DevOps modernes',
        date: DateTime.fromISO('2025-07-01T18:30:00'),
        location: 'Toulon, France',
        image: 'https://example.com/event14.jpg',
        maxParticipants: 30,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Formation React',
        description: 'Maîtrisez React et ses écosystèmes',
        date: DateTime.fromISO('2025-08-15T09:00:00'),
        location: 'Nancy, France',
        image: 'https://example.com/event15.jpg',
        maxParticipants: 20,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: "Salon de l'Innovation",
        description: 'Innovations technologiques',
        date: DateTime.fromISO('2025-09-20T10:00:00'),
        location: 'Dijon, France',
        image: 'https://example.com/event16.jpg',
        maxParticipants: 150,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Webinaire IA',
        description: 'Intelligence Artificielle appliquée',
        date: DateTime.fromISO('2025-10-05T14:00:00'),
        location: 'En ligne',
        image: 'https://example.com/event17.jpg',
        maxParticipants: 100,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Conférence Mobile',
        description: 'Développement mobile avancé',
        date: DateTime.fromISO('2025-11-15T09:00:00'),
        location: 'Angers, France',
        image: 'https://example.com/event18.jpg',
        maxParticipants: 70,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop Vue.js',
        description: 'Développement avec Vue.js',
        date: DateTime.fromISO('2025-12-01T10:00:00'),
        location: 'Tours, France',
        image: 'https://example.com/event19.jpg',
        maxParticipants: 25,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup Cloud Native',
        description: 'Architectures cloud-native',
        date: DateTime.fromISO('2026-01-20T18:30:00'),
        location: 'Reims, France',
        image: 'https://example.com/event20.jpg',
        maxParticipants: 40,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Hackathon Web3',
        description: 'Développement Web3 et blockchain',
        date: DateTime.fromISO('2026-02-15T08:00:00'),
        location: 'Clermont-Ferrand, France',
        image: 'https://example.com/event21.jpg',
        maxParticipants: 50,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Conférence DevOps',
        description: 'Pratiques DevOps avancées',
        date: DateTime.fromISO('2026-03-10T09:00:00'),
        location: 'Limoges, France',
        image: 'https://example.com/event22.jpg',
        maxParticipants: 80,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop Angular',
        description: 'Développement avec Angular',
        date: DateTime.fromISO('2026-04-05T10:00:00'),
        location: 'Poitiers, France',
        image: 'https://example.com/event23.jpg',
        maxParticipants: 20,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup Microservices',
        description: 'Architecture microservices',
        date: DateTime.fromISO('2026-05-20T18:30:00'),
        location: 'Caen, France',
        image: 'https://example.com/event24.jpg',
        maxParticipants: 35,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Formation Python',
        description: 'Python avancé et data science',
        date: DateTime.fromISO('2026-06-15T09:00:00'),
        location: 'Brest, France',
        image: 'https://example.com/event25.jpg',
        maxParticipants: 25,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Salon du Digital',
        description: 'Transformation digitale',
        date: DateTime.fromISO('2026-07-01T10:00:00'),
        location: 'Amiens, France',
        image: 'https://example.com/event26.jpg',
        maxParticipants: 180,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Webinaire Cloud',
        description: 'Solutions cloud modernes',
        date: DateTime.fromISO('2026-08-15T14:00:00'),
        location: 'En ligne',
        image: 'https://example.com/event27.jpg',
        maxParticipants: 100,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
    ])

    for (const user of users) {
      const numberOfEvents = Math.floor(Math.random() * 10)
      const randomEvents = await Event.query().orderByRaw('RANDOM()').limit(numberOfEvents)
      for (const event of randomEvents) {
        await event.related('participants').attach([user.id])
      }
    }
  }
}
