import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Event from '#models/event'
import { DateTime } from 'luxon'
import User from '#models/user'

export default class extends BaseSeeder {
  async run() {
    const users = await User.all()

    await Event.createMany([
      {
        title: 'Conférence Tech 2024',
        description: 'Une conférence sur les dernières technologies',
        date: DateTime.fromISO('2024-06-15T09:00:00'),
        location: 'Paris, France',
        image: 'https://picsum.photos/1000/500?random=1',
        maxParticipants: 100,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop Développement Web',
        description: 'Apprentissage des bases du développement web',
        date: DateTime.fromISO('2024-07-01T10:00:00'),
        location: 'Lyon, France',
        image: 'https://picsum.photos/1000/500?random=2',
        maxParticipants: 30,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Hackathon Innovation',
        description: '48h de développement intensif',
        date: DateTime.fromISO('2024-08-20T08:00:00'),
        location: 'Bordeaux, France',
        image: 'https://picsum.photos/1000/500?random=3',
        maxParticipants: 50,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup AI & ML',
        description: "Échanges sur l'intelligence artificielle",
        date: DateTime.fromISO('2024-09-10T18:30:00'),
        location: 'Toulouse, France',
        image: 'https://picsum.photos/1000/500?random=4',
        maxParticipants: 40,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Formation DevOps',
        description: 'Maîtrisez les outils DevOps',
        date: DateTime.fromISO('2024-10-05T09:00:00'),
        location: 'Nantes, France',
        image: 'https://picsum.photos/1000/500?random=5',
        maxParticipants: 25,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Salon du Numérique',
        description: 'Découverte des innovations digitales',
        date: DateTime.fromISO('2024-11-15T10:00:00'),
        location: 'Lille, France',
        image: 'https://picsum.photos/1000/500?random=6',
        maxParticipants: 200,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Webinaire Cybersécurité',
        description: 'Protection des données sensibles',
        date: DateTime.fromISO('2024-12-01T14:00:00'),
        location: 'En ligne',
        image: 'https://picsum.photos/1000/500?random=7',
        maxParticipants: 100,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Conférence Blockchain',
        description: "L'avenir de la blockchain",
        date: DateTime.fromISO('2025-01-20T09:00:00'),
        location: 'Marseille, France',
        image: 'https://picsum.photos/1000/500?random=8',
        maxParticipants: 80,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop UI/UX',
        description: "Design d'interfaces modernes",
        date: DateTime.fromISO('2025-02-10T10:00:00'),
        location: 'Strasbourg, France',
        image: 'https://picsum.photos/1000/500?random=9',
        maxParticipants: 20,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup Cloud Computing',
        description: 'Solutions cloud innovantes',
        date: DateTime.fromISO('2025-03-05T18:30:00'),
        location: 'Nice, France',
        image: 'https://picsum.photos/1000/500?random=10',
        maxParticipants: 35,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Hackathon Mobile',
        description: "Développement d'applications mobiles",
        date: DateTime.fromISO('2025-04-15T08:00:00'),
        location: 'Montpellier, France',
        image: 'https://picsum.photos/1000/500?random=11',
        maxParticipants: 60,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Conférence Big Data',
        description: 'Analyse de données massives',
        date: DateTime.fromISO('2025-05-20T09:00:00'),
        location: 'Rennes, France',
        image: 'https://picsum.photos/1000/500?random=12',
        maxParticipants: 90,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop IoT',
        description: 'Internet des Objets et applications',
        date: DateTime.fromISO('2025-06-10T10:00:00'),
        location: 'Grenoble, France',
        image: 'https://picsum.photos/1000/500?random=13',
        maxParticipants: 25,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup DevOps',
        description: 'Pratiques DevOps modernes',
        date: DateTime.fromISO('2025-07-01T18:30:00'),
        location: 'Toulon, France',
        image: 'https://picsum.photos/1000/500?random=14',
        maxParticipants: 30,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Formation React',
        description: 'Maîtrisez React et ses écosystèmes',
        date: DateTime.fromISO('2025-08-15T09:00:00'),
        location: 'Nancy, France',
        image: 'https://picsum.photos/1000/500?random=15',
        maxParticipants: 20,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: "Salon de l'Innovation",
        description: 'Innovations technologiques',
        date: DateTime.fromISO('2025-09-20T10:00:00'),
        location: 'Dijon, France',
        image: 'https://picsum.photos/1000/500?random=16',
        maxParticipants: 150,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Webinaire IA',
        description: 'Intelligence Artificielle appliquée',
        date: DateTime.fromISO('2025-10-05T14:00:00'),
        location: 'En ligne',
        image: 'https://picsum.photos/1000/500?random=17',
        maxParticipants: 100,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Conférence Mobile',
        description: 'Développement mobile avancé',
        date: DateTime.fromISO('2025-11-15T09:00:00'),
        location: 'Angers, France',
        image: 'https://picsum.photos/1000/500?random=18',
        maxParticipants: 70,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop Vue.js',
        description: 'Développement avec Vue.js',
        date: DateTime.fromISO('2025-12-01T10:00:00'),
        location: 'Tours, France',
        image: 'https://picsum.photos/1000/500?random=19',
        maxParticipants: 25,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup Cloud Native',
        description: 'Architectures cloud-native',
        date: DateTime.fromISO('2026-01-20T18:30:00'),
        location: 'Reims, France',
        image: 'https://picsum.photos/1000/500?random=20',
        maxParticipants: 40,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Hackathon Web3',
        description: 'Développement Web3 et blockchain',
        date: DateTime.fromISO('2026-02-15T08:00:00'),
        location: 'Clermont-Ferrand, France',
        image: 'https://picsum.photos/1000/500?random=21',
        maxParticipants: 50,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Conférence DevOps',
        description: 'Pratiques DevOps avancées',
        date: DateTime.fromISO('2026-03-10T09:00:00'),
        location: 'Limoges, France',
        image: 'https://picsum.photos/1000/500?random=22',
        maxParticipants: 80,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Workshop Angular',
        description: 'Développement avec Angular',
        date: DateTime.fromISO('2026-04-05T10:00:00'),
        location: 'Poitiers, France',
        image: 'https://picsum.photos/1000/500?random=23',
        maxParticipants: 20,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Meetup Microservices',
        description: 'Architecture microservices',
        date: DateTime.fromISO('2026-05-20T18:30:00'),
        location: 'Caen, France',
        image: 'https://picsum.photos/1000/500?random=24',
        maxParticipants: 35,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Formation Python',
        description: 'Python avancé et data science',
        date: DateTime.fromISO('2026-06-15T09:00:00'),
        location: 'Brest, France',
        image: 'https://picsum.photos/1000/500?random=25',
        maxParticipants: 25,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Salon du Digital',
        description: 'Transformation digitale',
        date: DateTime.fromISO('2026-07-01T10:00:00'),
        location: 'Amiens, France',
        image: 'https://picsum.photos/1000/500?random=26',
        maxParticipants: 180,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
      {
        title: 'Webinaire Cloud',
        description: 'Solutions cloud modernes',
        date: DateTime.fromISO('2026-08-15T14:00:00'),
        location: 'En ligne',
        image: 'https://picsum.photos/1000/500?random=27',
        maxParticipants: 100,
        userId: users[Math.floor(Math.random() * users.length)].id,
      },
    ])

    for (const user of users) {
      const numberOfEvents = Math.floor(Math.random() * 10)
      const randomEvents = await Event.query().orderByRaw('RANDOM()').limit(numberOfEvents)
      for (const event of randomEvents) {
        await event.related('participants').attach([user.id])
      }
    }
  }
}
