import { BaseSeeder } from '@adonisjs/lucid/seeders'
import ShopItem from '#models/shop_item'
import User from '#models/user'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    const users = await User.all()
    if (users.length === 0) {
      console.log('No users found. Please run the users seeder first.')
      return
    }

    const items = [
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Headset Pro',
        description:
          'High-quality wireless gaming headset with noise cancellation and RGB lighting',
        price: 12999,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Mechanical Keyboard',
        description: 'RGB mechanical keyboard with Cherry MX switches and customizable macros',
        price: 8999,
        image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Mouse',
        description: 'High-DPI gaming mouse with programmable buttons and RGB lighting',
        price: 5999,
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Chair',
        description: 'Ergonomic gaming chair with lumbar support and adjustable armrests',
        price: 29999,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Monitor',
        description: '27-inch 144Hz gaming monitor with 1ms response time and FreeSync',
        price: 39999,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Mousepad',
        description: 'Extended RGB gaming mousepad with non-slip base and stitched edges',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Webcam HD',
        description: '1080p HD webcam with autofocus and built-in microphone',
        price: 7999,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Microphone USB',
        description: 'Professional USB condenser microphone with pop filter',
        price: 12999,
        image: 'https://images.unsplash.com/photo-1598387993449-5b5c5c5c5c5c?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Streaming Light',
        description: 'Ring light with adjustable brightness and color temperature',
        price: 4999,
        image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Controller',
        description: 'Wireless gaming controller with vibration feedback and rechargeable battery',
        price: 6999,
        image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Headset Stand',
        description: 'RGB headset stand with USB hub and audio passthrough',
        price: 3999,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Cable Management Kit',
        description: 'Complete cable management solution with clips, ties, and sleeves',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Desk',
        description: 'Large gaming desk with cable management and cup holder',
        price: 19999,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Monitor Arm',
        description: 'Dual monitor arm with gas spring and cable management',
        price: 8999,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Socks',
        description: 'Comfortable gaming socks with anti-slip grip and moisture-wicking',
        price: 999,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Gloves',
        description: 'Fingerless gaming gloves with grip enhancement and breathable fabric',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Wrist Rest',
        description: 'Ergonomic wrist rest for keyboard and mouse with memory foam',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Mug',
        description: 'Insulated gaming mug with LED base and temperature display',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming T-Shirt',
        description: 'Comfortable gaming t-shirt with moisture-wicking technology',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Hoodie',
        description: 'Warm gaming hoodie with thumb holes and kangaroo pocket',
        price: 4999,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Cap',
        description: 'Adjustable gaming cap with embroidered logo and curved brim',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Backpack',
        description: 'Large gaming backpack with laptop compartment and cable organization',
        price: 7999,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Laptop Stand',
        description: 'Adjustable laptop stand with cooling fans and USB ports',
        price: 3999,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Cooling Pad',
        description: 'USB-powered cooling pad with adjustable fan speeds',
        price: 2999,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Power Bank',
        description: 'High-capacity power bank with fast charging and multiple ports',
        price: 5999,
        image: 'https://images.unsplash.com/photo-1609592806598-04d4d76d7173?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Cable',
        description: 'Braided USB-C cable with gold-plated connectors',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Adapter',
        description: 'Multi-port USB adapter with HDMI and Ethernet',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Surge Protector',
        description: 'Surge protector with USB charging ports and LED indicators',
        price: 3999,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Extension Cord',
        description: 'Heavy-duty extension cord with multiple outlets',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Wall Mount',
        description: 'VESA wall mount for monitors with cable management',
        price: 4999,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Shelf',
        description: 'Floating shelf for gaming accessories and collectibles',
        price: 3499,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Storage Box',
        description: 'Organized storage box for cables and small accessories',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Tool Kit',
        description: 'Complete tool kit for PC building and maintenance',
        price: 3999,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Cleaning Kit',
        description: 'Professional cleaning kit for electronics and peripherals',
        price: 2499,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Air Duster',
        description: 'Compressed air duster for cleaning keyboards and electronics',
        price: 999,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Screen Cleaner',
        description: 'Professional screen cleaner with microfiber cloth',
        price: 1499,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Anti-Static Mat',
        description: 'Anti-static mat for PC building and maintenance',
        price: 1999,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Thermal Paste',
        description: 'High-performance thermal paste for CPU and GPU',
        price: 999,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Cable Ties',
        description: 'Reusable cable ties for cable management',
        price: 499,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Stickers',
        description: 'Decorative stickers for gaming setup customization',
        price: 799,
        image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400',
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Headset Pro',
        description:
          'High-quality wireless gaming headset with noise cancellation and RGB lighting',
        price: 12999,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
        datePurchase: DateTime.now().minus({ days: 15 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Mechanical Keyboard',
        description: 'RGB mechanical keyboard with Cherry MX switches and customizable macros',
        price: 8999,
        image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400',
        datePurchase: DateTime.now().minus({ days: 12 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Mouse',
        description: 'High-DPI gaming mouse with programmable buttons and RGB lighting',
        price: 5999,
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400',
        datePurchase: DateTime.now().minus({ days: 8 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Chair',
        description: 'Ergonomic gaming chair with lumbar support and adjustable armrests',
        price: 29999,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
        datePurchase: DateTime.now().minus({ days: 20 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Monitor',
        description: '27-inch 144Hz gaming monitor with 1ms response time and FreeSync',
        price: 39999,
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400',
        datePurchase: DateTime.now().minus({ days: 25 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Webcam HD',
        description: '1080p HD webcam with autofocus and built-in microphone',
        price: 7999,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
        datePurchase: DateTime.now().minus({ days: 5 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Microphone USB',
        description: 'Professional USB condenser microphone with pop filter',
        price: 12999,
        image: 'https://images.unsplash.com/photo-1598387993449-5b5c5c5c5c5c?w=400',
        datePurchase: DateTime.now().minus({ days: 10 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Controller',
        description: 'Wireless gaming controller with vibration feedback and rechargeable battery',
        price: 6999,
        image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400',
        datePurchase: DateTime.now().minus({ days: 3 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Desk',
        description: 'Large gaming desk with cable management and cup holder',
        price: 19999,
        image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400',
        datePurchase: DateTime.now().minus({ days: 18 }),
      },
      {
        ownerId: users[Math.floor(Math.random() * users.length)].id,
        clientId: users[Math.floor(Math.random() * users.length)].id,
        name: 'Gaming Backpack',
        description: 'Large gaming backpack with laptop compartment and cable organization',
        price: 7999,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
        datePurchase: DateTime.now().minus({ days: 1 }),
      },
    ]

    await ShopItem.createMany(items)
    console.log('Shop items seeded successfully ! 🛒')
  }
}
