import User from '#models/user'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { UserRole } from '../../app/types/user_role.enum.js'

export default class extends BaseSeeder {
  async run() {
    await User.createMany([
      {
        username: 'admin',
        firstName: 'Admin',
        lastName: 'Admin',
        email: 'admin@example.com',
        password: 'password',
        birthDate: new Date('1990-01-01'),
        role: UserRole.ADMIN,
        novaPoints: 1000,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'sagby',
        firstName: 'Sagby',
        lastName: 'Sagby',
        email: 'sagby@example.com',
        password: 'password',
        birthDate: new Date('1990-01-01'),
        role: UserRole.SUPERADMIN,
        novaPoints: 2000,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'johndoe',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john@example.com',
        password: 'password',
        birthDate: new Date('1992-05-15'),
        role: UserRole.USER,
        novaPoints: 500,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'janedoe',
        firstName: 'Jane',
        lastName: 'Doe',
        email: 'jane@example.com',
        password: 'password',
        birthDate: new Date('1993-08-20'),
        role: UserRole.USER,
        novaPoints: 750,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'banned_user1',
        firstName: 'Bad',
        lastName: 'User',
        email: 'bad@example.com',
        password: 'password',
        birthDate: new Date('1991-03-10'),
        role: UserRole.USER,
        novaPoints: 0,
        isBanned: true,
        banReason: 'Spamming',
        avatar: null,
      },
      {
        username: 'marie_curie',
        firstName: 'Marie',
        lastName: 'Curie',
        email: 'marie@example.com',
        password: 'password',
        birthDate: new Date('1994-11-30'),
        role: UserRole.USER,
        novaPoints: 1200,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'albert_einstein',
        firstName: 'Albert',
        lastName: 'Einstein',
        email: 'albert@example.com',
        password: 'password',
        birthDate: new Date('1995-04-18'),
        role: UserRole.USER,
        novaPoints: 1500,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'banned_user2',
        firstName: 'Toxic',
        lastName: 'User',
        email: 'toxic@example.com',
        password: 'password',
        birthDate: new Date('1992-07-22'),
        role: UserRole.USER,
        novaPoints: 0,
        isBanned: true,
        banReason: 'Harassment',
        avatar: null,
      },
      {
        username: 'emma_watson',
        firstName: 'Emma',
        lastName: 'Watson',
        email: 'emma@example.com',
        password: 'password',
        birthDate: new Date('1996-09-15'),
        role: UserRole.USER,
        novaPoints: 800,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'chris_hemsworth',
        firstName: 'Chris',
        lastName: 'Hemsworth',
        email: 'chris@example.com',
        password: 'password',
        birthDate: new Date('1993-12-25'),
        role: UserRole.USER,
        novaPoints: 950,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'banned_user3',
        firstName: 'Scam',
        lastName: 'Artist',
        email: 'scam@example.com',
        password: 'password',
        birthDate: new Date('1991-06-30'),
        role: UserRole.USER,
        novaPoints: 0,
        isBanned: true,
        banReason: 'Fraudulent activity',
        avatar: null,
      },
      {
        username: 'sophie_turner',
        firstName: 'Sophie',
        lastName: 'Turner',
        email: 'sophie@example.com',
        password: 'password',
        birthDate: new Date('1997-02-21'),
        role: UserRole.USER,
        novaPoints: 1100,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'tom_holland',
        firstName: 'Tom',
        lastName: 'Holland',
        email: 'tom@example.com',
        password: 'password',
        birthDate: new Date('1996-06-01'),
        role: UserRole.USER,
        novaPoints: 1300,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'banned_user4',
        firstName: 'Hate',
        lastName: 'Speech',
        email: 'hate@example.com',
        password: 'password',
        birthDate: new Date('1994-03-15'),
        role: UserRole.USER,
        novaPoints: 0,
        isBanned: true,
        banReason: 'Hate speech',
        avatar: null,
      },
      {
        username: 'zendaya',
        firstName: 'Zendaya',
        lastName: 'Coleman',
        email: 'zendaya@example.com',
        password: 'password',
        birthDate: new Date('1996-09-01'),
        role: UserRole.USER,
        novaPoints: 1600,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'timothee_chalamet',
        firstName: 'Timothée',
        lastName: 'Chalamet',
        email: 'timothee@example.com',
        password: 'password',
        birthDate: new Date('1995-12-27'),
        role: UserRole.USER,
        novaPoints: 1400,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'banned_user5',
        firstName: 'Spam',
        lastName: 'Bot',
        email: 'spam@example.com',
        password: 'password',
        birthDate: new Date('1993-10-10'),
        role: UserRole.USER,
        novaPoints: 0,
        isBanned: true,
        banReason: 'Bot activity',
        avatar: null,
      },
      {
        username: 'florence_pugh',
        firstName: 'Florence',
        lastName: 'Pugh',
        email: 'florence@example.com',
        password: 'password',
        birthDate: new Date('1996-01-03'),
        role: UserRole.USER,
        novaPoints: 900,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'robert_pattinson',
        firstName: 'Robert',
        lastName: 'Pattinson',
        email: 'robert@example.com',
        password: 'password',
        birthDate: new Date('1986-05-13'),
        role: UserRole.USER,
        novaPoints: 1700,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'banned_user6',
        firstName: 'Fake',
        lastName: 'News',
        email: 'fake@example.com',
        password: 'password',
        birthDate: new Date('1992-12-12'),
        role: UserRole.USER,
        novaPoints: 0,
        isBanned: true,
        banReason: 'Spreading misinformation',
        avatar: null,
      },
      {
        username: 'anya_taylor_joy',
        firstName: 'Anya',
        lastName: 'Taylor-Joy',
        email: 'anya@example.com',
        password: 'password',
        birthDate: new Date('1996-04-16'),
        role: UserRole.USER,
        novaPoints: 1250,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'barry_keoghan',
        firstName: 'Barry',
        lastName: 'Keoghan',
        email: 'barry@example.com',
        password: 'password',
        birthDate: new Date('1992-10-18'),
        role: UserRole.USER,
        novaPoints: 1150,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'banned_user7',
        firstName: 'Troll',
        lastName: 'Master',
        email: 'troll@example.com',
        password: 'password',
        birthDate: new Date('1995-08-08'),
        role: UserRole.USER,
        novaPoints: 0,
        isBanned: true,
        banReason: 'Trolling behavior',
        avatar: null,
      },
      {
        username: 'margot_robbie',
        firstName: 'Margot',
        lastName: 'Robbie',
        email: 'margot@example.com',
        password: 'password',
        birthDate: new Date('1990-07-02'),
        role: UserRole.USER,
        novaPoints: 1800,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
      {
        username: 'ryan_gosling',
        firstName: 'Ryan',
        lastName: 'Gosling',
        email: 'ryan@example.com',
        password: 'password',
        birthDate: new Date('1980-11-12'),
        role: UserRole.USER,
        novaPoints: 1650,
        isBanned: false,
        banReason: null,
        avatar: null,
      },
    ])

    console.log('Users seeded successfully ! 🧑‍🤝‍🧑')
  }
}
