export enum NotificationType {
  POST_LIKE = 'POST_LIKE',
  POST_COMMENT = 'POST_COMMENT',
  COMMENT_LIKE = 'COMMENT_LIKE',
  EVENT_SUBSCRIBE = 'EVENT_SUBSCRIBE',
  EVENT_UNSUBSCRIBE = 'EVENT_UNSUBSCRIBE',
  NOVA_POINTS_ADDED = 'NOVA_POINTS_ADDED',
  NOVA_POINTS_REMOVED = 'NOVA_POINTS_REMOVED',
  SERVICE_VOLUNTEER = 'SERVICE_VOLUNTEER',
  SERVICE_UNVOLUNTEER = 'SERVICE_UNVOLUNTEER',
}
